title: Your awesome title
author:
  name: GitHub User
  email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

show_excerpts: false # set to true to show excerpts on the homepage

# Build settings
theme: minima

# date format
# Reference https://shopify.github.io/liquid/filters/date/
minima:
  date_format: "%b %-d, %Y"

  # social links displayed in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # googleplus: +jekyll
    # instagram: jekyll
    # keybase: jekyll
    # linkedin: jekyll
    # microdotblog: jekyll
    # pinterest: jekyll
    # telegram: jekyll
    # youtube_channel_name: CloudCannon
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in the header, uncomment
# this and add the path to the pages in order as they should show up.
#header_pages:
# - about.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
